from pathlib import Path

path = Path('src/features/notes/NotesWorkspace.tsx')
text = path.read_text(encoding='utf-8')
old = '''  useEffect(() => {\n    const tabs = folderTabsRef.current\n    if (!tabs) return\n\n    function updateHint() {\n      const overflow = tabs.scrollWidth > tabs.clientWidth + 4\n      if (!overflow) {\n        setFolderScrollHint(null)\n        return\n      }\n      const hasRight = tabs.scrollLeft + tabs.clientWidth < tabs.scrollWidth - 4\n      setFolderScrollHint(hasRight ? 'right' : tabs.scrollLeft > 4 ? 'left' : null)\n    }\n\n    const frame = window.requestAnimationFrame(updateHint)\n    const observer = typeof ResizeObserver === 'undefined' ? null : new ResizeObserver(updateHint)\n    observer?.observe(tabs)\n    window.addEventListener('resize', updateHint)\n    return () => {\n      window.cancelAnimationFrame(frame)\n      observer?.disconnect()\n      window.removeEventListener('resize', updateHint)\n    }\n  }, [folders.length])\n'''
new = '''  useEffect(() => {\n    const observedTabs = folderTabsRef.current\n    if (!observedTabs) return\n\n    function updateHint() {\n      const tabs = folderTabsRef.current\n      if (!tabs) return\n      const overflow = tabs.scrollWidth > tabs.clientWidth + 4\n      if (!overflow) {\n        setFolderScrollHint(null)\n        return\n      }\n      const hasRight = tabs.scrollLeft + tabs.clientWidth < tabs.scrollWidth - 4\n      setFolderScrollHint(hasRight ? 'right' : tabs.scrollLeft > 4 ? 'left' : null)\n    }\n\n    const frame = window.requestAnimationFrame(updateHint)\n    const observer = typeof ResizeObserver === 'undefined' ? null : new ResizeObserver(updateHint)\n    observer?.observe(observedTabs)\n    window.addEventListener('resize', updateHint)\n    return () => {\n      window.cancelAnimationFrame(frame)\n      observer?.disconnect()\n      window.removeEventListener('resize', updateHint)\n    }\n  }, [folders.length])\n'''
if old not in text:
    raise SystemExit('Expected folder tabs effect not found')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
