import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const runtime = readFileSync('src/features/notes/NoteListReorderGestureRuntime.tsx', 'utf8')
const css = readFileSync('src/features/notes/noteReorderGesture.css', 'utf8')
const workspace = readFileSync('src/features/notes/NotesWorkspace.tsx', 'utf8')
const avatar = readFileSync('src/features/notes/NoteAvatar.tsx', 'utf8')
const privacyRuntime = readFileSync('src/features/privacy/NoteBulkPrivacyRuntime.tsx', 'utf8')
const app = readFileSync('src/app/App.tsx', 'utf8')
const pkg = readFileSync('package.json', 'utf8')

test('reorder móvil queda bajo Pointer Events y SortableJS se reserva para escritorio', () => {
  assert.match(pkg, /"sortablejs": "1\.15\.7"/)
  assert.match(runtime, /import Sortable from 'sortablejs'/)
  assert.match(runtime, /Sortable\.create\(list/)
  assert.match(runtime, /disabled: coarsePointer/)
  assert.match(runtime, /const LONG_PRESS_MS = 220/)
  assert.match(runtime, /const TOUCH_MOVE_CANCEL_PX = 12/)
  assert.match(runtime, /event\.pointerType === 'mouse'/)
  assert.match(runtime, /setPointerCapture\(touchGesture\.pointerId\)/)
  assert.match(runtime, /const SCROLL_START_PX = 4/)
  assert.match(runtime, /list\.scrollTop -= fingerDeltaY/)
  assert.match(runtime, /startScrollMomentum\(finished\.scrollVelocityY\)/)
  assert.match(runtime, /FLING_FRICTION_PER_FRAME/)
  assert.match(runtime, /window\.scrollTo\(0, touchGesture\.startWindowScrollY - dy\)/)
  assert.match(css, /touch-action: none !important/)
  assert.doesNotMatch(runtime, /TouchEvent|onNativeTouch/)
})

test('toda la fila es superficie de drag y los controles reales quedan excluidos', () => {
  assert.match(runtime, /handle: '\.note-row\[data-reorder-note-id\]'/)
  assert.match(runtime, /function isExcludedInteractiveTarget/)
  assert.match(runtime, /\.note-row__menu-wrap/)
  assert.match(runtime, /button:not\(\.note-row__open\)/)
  assert.match(runtime, /interactionBlocked\(\) \|\| isExcludedInteractiveTarget\(target\)/)
  assert.match(workspace, /className="note-row__open"/)
  assert.match(workspace, /NoteAvatar[\s\S]*?className="note-row__avatar"/)
  assert.match(avatar, /className=\{className\}/)
  assert.match(css, /\.note-row\[data-reorder-note-id\],\s*\n\.note-row\[data-reorder-note-id\] \.note-row__open/)
  assert.match(css, /cursor:\s*grab/)
  assert.match(css, /@media \(pointer: coarse\)[\s\S]*?touch-action:\s*none !important/)
  assert.doesNotMatch(runtime, /touchArmTimer|touchArmed/)
})

test('instrumentación temporal de drag fue retirada después del diagnóstico', () => {
  assert.doesNotMatch(runtime, /__OANIX_NOTE_DRAG_TRACE__/)
  assert.doesNotMatch(runtime, /Drag logs/)
  assert.doesNotMatch(runtime, /onPointerMoveDiagnostic|onTouchMoveDiagnostic/)
})

test('la tarjeta visible usa un overlay independiente y sigue directamente el dedo', () => {
  assert.match(runtime, /forceFallback: true/)
  assert.match(runtime, /fallbackOnBody: true/)
  assert.match(runtime, /fallbackTolerance: 4/)
  assert.match(runtime, /fallbackClass: 'oanix-mobile-note-drag-ghost'/)
  assert.match(runtime, /ghostClass: 'oanix-mobile-note-placeholder'/)
  assert.match(runtime, /cloneNode\(true\)/)
  assert.match(runtime, /clone\.classList\.add\('oanix-mobile-note-drag-overlay'\)/)
  assert.doesNotMatch(runtime, /clone\.className = 'oanix-mobile-note-drag-overlay'/)
  assert.match(runtime, /dragOverlay/)
  assert.match(runtime, /createDragOverlay\(event\.item/)
  assert.match(runtime, /document\.addEventListener\('pointermove'/)
  assert.doesNotMatch(runtime, /document\.addEventListener\('touchmove'/)
  assert.match(css, /.notes-shell > \.note-row\.oanix-mobile-note-drag-overlay[\s\S]*?position:\s*fixed !important/)
  assert.match(css, /.notes-shell > \.note-row\.oanix-mobile-note-drag-overlay[\s\S]*?z-index:\s*10050 !important/)
  assert.match(css, /.notes-shell > \.note-row\.oanix-mobile-note-drag-overlay[\s\S]*?pointer-events:\s*none !important/)
  assert.match(css, /\.note-row\.oanix-mobile-note-placeholder[\s\S]*?border:\s*2px dashed/)
  assert.match(css, /\.note-row\.oanix-mobile-note-placeholder > \*[\s\S]*?visibility:\s*hidden !important/)
  assert.match(css, /@keyframes oanix-note-drop-slot-pulse/)
})

test('overlay independiente mantiene visible todo el contenido y la superficie real de la nota', () => {
  assert.match(css, /.notes-shell > \.note-row\.oanix-mobile-note-drag-overlay > \*[\s\S]*visibility:\s*visible !important[\s\S]*opacity:\s*1 !important/)
  assert.match(css, /.notes-shell > \.note-row\.oanix-mobile-note-drag-overlay::after\s*\{[\s\S]*opacity:\s*1 !important/)
  assert.match(css, /.notes-shell > \.note-row\.oanix-mobile-note-drag-overlay \.note-row__avatar[\s\S]*visibility:\s*visible !important/)
  assert.match(css, /.notes-shell > \.note-row\.oanix-mobile-note-drag-overlay[\s\S]*background:\s*var\(--oanix-note-drag-background\) !important/)
  assert.match(runtime, /clone\.style\.setProperty\('overflow', 'visible', 'important'\)/)
  assert.doesNotMatch(runtime, /clone\.style\.setProperty\('background'/)
  assert.doesNotMatch(runtime, /clone\.style\.setProperty\('overflow', 'hidden'/)
  assert.match(runtime, /const overlayHost = list\.closest<HTMLElement>\('\.notes-shell'\) \?\? document\.body/)
  assert.match(runtime, /overlayHost\.appendChild\(clone\)/)
  assert.match(runtime, /removeDragOverlay\(\)/)
})

test('identidad visual se congela por note id durante el drag y se restaura antes de persistir', () => {
  assert.match(runtime, /const dragIdentityById = new Map<string, DragIdentity>\(\)/)
  assert.match(runtime, /freezeDragIdentity\(\)/)
  assert.match(runtime, /restoreDragIdentity\(\)/)
  assert.match(runtime, /--oanix-note-drag-stable-card-color/)
  assert.match(runtime, /--oanix-note-drag-stable-tab-color/)
  assert.match(runtime, /avatar\.dataset\.oanixNoteIcon = identity\.icon/)
  assert.match(css, /\.note-row\[data-oanix-note-stable-visual='true'\][\s\S]*--oanix-note-card-color:\s*var\(--oanix-note-stable-color\) !important/)
  assert.match(css, /\.note-row\[data-oanix-note-stable-visual='true'\][\s\S]*--oanix-note-tab-color:\s*var\(--oanix-note-stable-color\) !important/)
  assert.match(css, /--oanix-note-card-color:\s*var\(--oanix-note-drag-stable-card-color\) !important/)
  assert.match(css, /--oanix-note-tab-color:\s*var\(--oanix-note-drag-stable-tab-color\) !important/)
})

test('escritorio usa SortableJS y móvil mantiene orden vertical y auto-scroll propios', () => {
  assert.match(runtime, /direction: 'vertical'/)
  assert.match(runtime, /scroll: true/)
  assert.match(runtime, /scrollSensitivity: 72/)
  assert.match(runtime, /scrollSpeed: 12/)
  assert.match(runtime, /bubbleScroll: false/)
  assert.match(runtime, /swapThreshold: 0\.62/)
  assert.match(runtime, /function scrollSpeed\(clientY: number\)/)
  assert.match(runtime, /reorderTouchDomAtPoint\(touchGesture/)
  assert.match(runtime, /window\.scrollBy\(0, speed\)/)
})

test('notas fijadas y no fijadas no se mezclan', () => {
  assert.match(runtime, /function rowPinned/)
  assert.match(runtime, /const draggedPinned = rowPinned\(gesture\.item\)/)
  assert.match(runtime, /rowPinned\(event\.dragged\) === rowPinned\(event\.related\)/)
})

test('controles interactivos y selección múltiple no compiten con reorder', () => {
  assert.match(runtime, /function isExcludedInteractiveTarget/)
  assert.match(runtime, /interactionBlocked\(\) \|\| isExcludedInteractiveTarget\(target\)/)
  assert.match(runtime, /preventOnFilter: false/)
  assert.match(runtime, /oanix-note-bulk-selecting/)
  assert.match(privacyRuntime, /data-oanix-bulk-mode/)
})

test('orden persiste y sincroniza React sin remonte completo en el camino exitoso', () => {
  assert.match(runtime, /onEnd:/)
  assert.match(runtime, /const nextOrder = noteOrder\(event\.to\)/)
  assert.match(runtime, /const updatedNotes = await persistNoteOrder\(nextOrder\)/)
  assert.match(runtime, /oanix:note-order-persisted/)
  assert.match(runtime, /manualOrder: note\.manualOrder/)
  assert.match(workspace, /oanix:note-order-persisted/)
  assert.match(workspace, /manualOrderById/)
  assert.match(workspace, /\.sort\(compareNotesForList\)/)
  assert.match(runtime, /try \{[\s\S]*persistNoteOrder\(nextOrder\)[\s\S]*catch \{[\s\S]*oanix:workspace-refresh/)
  assert.doesNotMatch(runtime, /persistNoteOrder[\s\S]{0,120}onMove/)
})

test('dock de carpetas queda inmóvil e inerte mientras se arrastra una nota', () => {
  assert.match(css, /html\.oanix-mobile-note-dragging,\s*\nbody\.oanix-mobile-note-dragging\s*\{[\s\S]*?overflow:\s*hidden !important/)
  assert.match(css, /html\.oanix-mobile-note-dragging \.oanix-folder-grid/)
  assert.match(css, /position:\s*fixed !important/)
  assert.match(css, /inset:\s*auto 0 0 !important/)
  assert.match(css, /pointer-events:\s*none !important/)
  assert.match(css, /html\.oanix-mobile-note-dragging \.oanix-folder-rail/)
  assert.match(css, /transition:\s*none !important/)
})

test('selección y menú contextual nativos siguen bloqueados', () => {
  assert.match(css, /-webkit-user-select: none !important/)
  assert.match(css, /user-select: none !important/)
  assert.match(css, /-webkit-touch-callout: none !important/)
  assert.match(runtime, /contextmenu/)
  assert.match(runtime, /selectstart/)
  assert.match(runtime, /window\.getSelection\(\)\?\.removeAllRanges\(\)/)
})

test('NotesWorkspace no conserva otro motor de reorder', () => {
  assert.doesNotMatch(workspace, /reorderMode|orderingBusy|draggingNoteId|dragTargetId|dragPlacement/)
  assert.doesNotMatch(workspace, /handleReorderPointer|persistDraggedOrder|autoScrollNoteList/)
  assert.doesNotMatch(workspace, /ReactPointerEvent|persistNoteOrder/)
})

test('runtime queda ligado a la lista actual y React lo remonta con cada revision', () => {
  assert.match(runtime, /const list = document\.querySelector<HTMLElement>\('\.notes-list'\)/)
  assert.match(runtime, /list\?\.classList\.contains\('notes-list'\)/)
  assert.match(runtime, /sortable\.destroy\(\)/)
  assert.doesNotMatch(runtime, /new MutationObserver/)
  assert.match(app, /<NoteListReorderGestureRuntime key=\{`note-reorder-\$\{workspaceRevision\}`\} \/>/)
})
