import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const app = readFileSync('src/app/App.tsx', 'utf8')
const database = readFileSync('src/storage/local/database.ts', 'utf8')
const repository = readFileSync('src/storage/repositories/encryptedV2RecordRepository.ts', 'utf8')
const service = readFileSync('src/features/rebuild/rebuildService.ts', 'utf8')
const model = readFileSync('src/features/rebuild/rebuildModel.ts', 'utf8')
const rebuild = readFileSync('src/features/rebuild/RebuildApp.tsx', 'utf8')
const editorSurface = readFileSync('src/features/editor/EditorSurface.tsx', 'utf8')
const editorSurfaceRegistry = readFileSync('src/features/editor/editorSurfaceRegistry.ts', 'utf8')
const selectedEditorSurface = readFileSync('src/features/editor/implementations/OanixNotesSheetSurface.tsx', 'utf8')
const css = readFileSync('src/features/rebuild/rebuild.css', 'utf8')

test('post-unlock rebuild keeps the vault gate and replaces the old workspace authority', () => { assert.match(app, /<VaultGate/); assert.match(app, /<RebuildApp onLock=\{lockVault\} \/>/); assert.doesNotMatch(app, /<AutoSyncRuntime/); assert.doesNotMatch(app, /<NotesWorkspace/); assert.match(app, /<AndroidBackRuntime \/>/) })
test('v2 encrypted records use their own indexed additive store', () => { assert.match(database, /DATABASE_VERSION = 3/); assert.match(database, /V2_ENCRYPTED_RECORDS_STORE = 'encrypted_records_v2'/); assert.match(database, /keyPath: \['recordType', 'recordId'\]/); assert.match(database, /createIndex\(V2_RECORD_TYPE_INDEX, 'recordType'/); assert.match(repository, /\.index\(V2_RECORD_TYPE_INDEX\)/); assert.match(repository, /IDBKeyRange\.only\(recordType\)/); assert.doesNotMatch(repository, /\.getAll\(\)[\s\S]*parseEncryptedRecordKey/) })
test('v2 notes persist incrementally with manifest chunks and an encrypted pending queue', () => { assert.match(model, /NOTE_V2_META_TYPE = 'note\.v2\.meta'/); assert.match(model, /NOTE_V2_MANIFEST_TYPE = 'note\.v2\.manifest'/); assert.match(model, /NOTE_V2_TEXT_CHUNK_TYPE = 'note\.v2\.text-chunk'/); assert.match(model, /SYNC_V2_PENDING_TYPE = 'sync\.v2\.pending'/); assert.match(service, /buildInitialIncrementalText/); assert.match(service, /buildIncrementalTextUpdate/); assert.match(service, /readEncryptedV2Records<NoteV2TextChunk>/); assert.match(service, /applyEncryptedV2Changes\(\{ writes, deletes \}\)/); assert.match(service, /if \(!titleChanged && !textChanged\) return existing/); assert.match(repository, /export async function applyEncryptedV2Changes/); assert.match(repository, /encrypted\.forEach\(\(record\) => store\.put\(record\)\)/); assert.match(repository, /deletes\.forEach\(\(\{ recordType, recordId \}\) => store\.delete\(\[recordType, recordId\]\)\)/) })
test('legacy v2 whole-body notes are read only as a migration fallback', () => { assert.match(model, /NOTE_V2_BODY_TYPE = 'note\.v2\.body'/); assert.match(service, /Transitional fallback/); assert.match(service, /readEncryptedV2Record<NoteV2Body>\(NOTE_V2_BODY_TYPE, noteId\)/); assert.doesNotMatch(service, /recordType: NOTE_V2_BODY_TYPE, recordId: existing\.id/) })
test('typing stays local and persistence happens only at idle or close save boundaries', () => { assert.match(rebuild, /<EditorSurface/); assert.match(rebuild, /async function saveEditorSnapshot\(snapshot: EditorSurfaceSnapshot\)/); assert.match(rebuild, /async function closeEditor\(snapshot: EditorSurfaceSnapshot \| null\)/); assert.match(rebuild, /onRequestSave=\{saveEditorSnapshot\}/); assert.match(rebuild, /editorRef = useRef<OpenedEditor \| null>/); assert.match(rebuild, /current\.meta,[\s\S]*current\.text,[\s\S]*snapshot\.title,[\s\S]*snapshot\.text/); assert.match(editorSurface, /const ActiveSurface = lazy\(activeEditorSurface\.load\)/); assert.match(editorSurface, /<Suspense fallback=\{null\}>/); assert.match(editorSurface, /<ActiveSurface[\s\S]*\{\.\.\.surfaceProps\}[\s\S]*\/>/); assert.match(editorSurface, /installOanixTextBehaviorBridge/); assert.match(editorSurface, /key=\{behaviorRevision\}/); assert.match(editorSurface, /activeEditorSurface\.capabilities\.richBlocks/); assert.match(editorSurfaceRegistry, /await import\([\s\S]*OanixNotesSheetMobileGuard/); assert.match(selectedEditorSurface, /defaultValue=\{initialText\}/); assert.match(selectedEditorSurface, /defaultValue=\{initialTitle\}/); assert.match(selectedEditorSurface, /AUTOSAVE_IDLE_MS = 3_000/); assert.match(selectedEditorSurface, /generationRef/); assert.match(selectedEditorSurface, /saveInFlightRef/); assert.match(selectedEditorSurface, /async function saveCurrentSnapshot/); assert.match(selectedEditorSurface, /onRequestSave\(snapshot\)/); assert.match(selectedEditorSurface, /async function requestClose/); assert.match(selectedEditorSurface, /await onRequestClose\(snapshot\)/); assert.doesNotMatch(selectedEditorSurface, /value=\{.*initialText|setText\(|innerHTML|contentEditable|MutationObserver/); assert.doesNotMatch(selectedEditorSurface, /indexedDB|localStorage|sessionStorage/) })
test('slow operations expose delayed full-screen feedback instead of fake progress', () => { assert.match(rebuild, /useDelayedBusy\(saving\)/); assert.match(rebuild, /useDelayedBusy\(openingNote\)/); assert.match(rebuild, /className="rebuild-progress"/); assert.match(rebuild, /Cifrando y confirmando el guardado local/); assert.match(css, /\.rebuild-progress \{[\s\S]*position: fixed;[\s\S]*inset: 0;/); assert.match(css, /rebuildProgress/); assert.doesNotMatch(rebuild, /\d+%/) })
test('appearance is controlled from Settings without a duplicate top-bar toggle', () => { assert.match(rebuild, /<strong>Apariencia<\/strong>/); assert.match(rebuild, /chooseTheme\('classic-day'\)/); assert.match(rebuild, /chooseTheme\('classic-night'\)/); assert.doesNotMatch(rebuild, /Cambiar a modo día|Cambiar a modo noche/) })
test('folder identity and rebuild layout cover desktop mobile day and night', () => { assert.match(model, /V2_FOLDER_GRADIENTS/); assert.match(service, /gradientIndex: secureRandomIndex\(V2_FOLDER_GRADIENTS\.length\)/); assert.match(css, /\.rebuild-drawer__folder[\s\S]*background: var\(--folder-soft\)/); assert.match(css, /\.rebuild-notes::before[\s\S]*var\(--active-folder-cover/); assert.match(css, /data-oanix-theme-mode="light"/); assert.match(css, /@media \(max-width: 760px\)/); assert.match(css, /@media \(min-width: 900px\)/); assert.match(css, /env\(safe-area-inset-bottom\)/) })
